---
excerpt_separator: <!--more-->
baseurl: ""
kramdown:
  smart_quotes: ["apos","apos","quot","quot"]
  syntax_highlighter_opts:
    block:
      line_numbers: true
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      permalink: /:categories/:title
---

